services:
  - type: web
    name: easyGO-backend
    env: docker
    plan: starter
    rootDir: ./web-backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DB_SYNC
        value: "false"
      - key: DB_SYNC_ALTER
        value: "false"
      - key: FIREBASE_USE_ADC
        value: "false"
      - key: CORS_ORIGINS
        value: https://easygols.web.app,https://easygols.firebaseapp.com
